"""DEPRECATED — points at vLLM 0.8.5 / 120 s arm directories.

Use scripts/generate_launch_chart_v3.py instead. The v3 generator reads
from results/gate2_preprint_v3/ and produces the chart that matches the
launch post hero numbers (vLLM 0.19.1, 300 s sustained, n=311 post-warmup).

Running this script will produce a chart whose numbers don't match the
current launch narrative. Kept in tree only as historical reference for
how the original Gate 2-FAIRNESS chart was generated.
"""
import sys

print("DEPRECATED: scripts/generate_launch_chart.py points at the original")
print("vLLM 0.8.5 / 120s bench data. The launch post hero chart is now")
print("generated by scripts/generate_launch_chart_v3.py from the v3 preprint.")
print()
print("To regenerate the current hero chart:")
print("  python3 scripts/generate_launch_chart_v3.py")
print()
print("To inspect the original chart-generation logic, see git history:")
print("  git log --oneline -- scripts/generate_launch_chart.py")
sys.exit(2)
